# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy Laravel app to Azure Web App - backendV2

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Zip the public folder and vendor only
        run: |
          mkdir deploy
          cp -r public deploy/public
          cp -r vendor deploy/vendor
          cp -r bootstrap deploy/bootstrap
          cp -r storage deploy/storage
          cp -r .env deploy/.env || true
          zip -r release.zip deploy

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EB93B1324DD943DE8D9B958A367CA8FD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8A2793F9769A491B8BB2D419A0DB02F1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_565DF9AACCF64FDA83BAD04C8B331ECF }}

      - name: Deploy to Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backendV2'
          package: deploy
