name: Build and deploy Laravel app to Azure Web App - crud-larabel-web75a43994

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Create .env file
        run: cp .env.example .env

      - name: Generate APP_KEY
        run: php artisan key:generate --force

      - name: Cache Laravel config
        run: php artisan config:cache

      - name: Zip Laravel project
        run: |
          sudo apt-get update && sudo apt-get install -y zip
          zip -r release.zip . -x "*.git*" "node_modules/*" "vendor/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'crud-larabel-web75a43994'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4434431508FF49B38C6B866E6B7EABC9 }}
          package: .
