name: Build and deploy Laravel app to Azure Web App - laravel-backend-demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_sqlsrv, openssl

      - name: Install composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create .env file from secrets
        run: |
          echo "APP_NAME=LaravelApp" > .env
          echo "APP_ENV=${{ secrets.APP_ENV }}" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_DEBUG=${{ secrets.APP_DEBUG }}" >> .env
          echo "APP_URL=${{ secrets.APP_URL }}" >> .env
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "LOG_CHANNEL=stack" >> .env

      - name: Generate Laravel APP key
        run: php artisan key:generate --ansi

      - name: Set storage permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Zip app for deployment
        run: zip -r release.zip . -x "vendor/*" "node_modules/*" ".git/*" ".github/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'laravel-backend-demo'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: release.zip

      # Migración recomendada a ejecutarse manualmente por SSH luego del deploy
      - name: Recordatorio de migración
        run: echo "👉 Despliegue completado. Ejecuta 'php artisan migrate --force' desde el Web SSH de App Service."



