# .github/workflows/develop_laravel-backend-demo.yml

name: Build and deploy Laravel app to Azure Web App - laravel-backend-demo

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, openssl

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Set permissions for Laravel folders
        run: chmod -R 775 storage bootstrap/cache

      - name: Zip Laravel app for deployment
        run: |
          zip -r release.zip . -x "tests/*" "node_modules/*" ".git/*" ".github/*"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_436B9FF7EAEC4FA7A3DD1A871364D449 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5D56074C2AF548CA942F0F666E0E0E18 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AE9A0F88F2F54309ACDC02766A22CE68 }}

      - name: Prepare Laravel (config/cache/key)
        run: |
          composer dump-autoload --optimize
          php artisan key:generate --force
          php artisan config:clear
          php artisan config:cache
          php artisan route:cache

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'laravel-backend-demo'
          slot-name: 'Production'
          package: .
