name: Build and deploy Laravel to Azure Web App - backendV2

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, curl, xml, tokenizer, pdo, openssl

      - name: Install Composer Dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          php artisan key:generate --ansi
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          chmod -R 775 storage bootstrap/cache

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x ".git/" "node_modules/" "tests/" ".log"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EB93B1324DD943DE8D9B958A367CA8FD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8A2793F9769A491B8BB2D419A0DB02F1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_565DF9AACCF64FDA83BAD04C8B331ECF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'backendV2'
          slot-name: 'Production'
          package: .

      - name: Run Laravel migrations
        run: php artisan migrate --force || echo "Migración no aplicada (posiblemente ya ejecutada)"
