name: Build and deploy PHP Laravel app to Azure Web App - appserviceDojo14-04-2025

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, curl, mysql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader

      - name: Ensure storage and cache directories exist
        run: |
          mkdir -p storage/framework/{cache,sessions,views}
          mkdir -p bootstrap/cache

      - name: Copy .env.production to .env
        run: cp .env.production .env

      - name: Set Laravel App Key
        run: php artisan key:generate || echo "Key already set"

      - name: Cache Config, Routes, Views
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x ".git" "tests/" "node_modules/" "storage/logs/" ".github/"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_53A524527954481D988C3A7518061EE5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B4A9DB7B34704212A521FF6735026CEB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_62BF135F4C8249ED92453D2C8EC894C6 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'appserviceDojo14-04-2025'
          slot-name: 'Production'
          package: .
