name: Build and deploy Laravel app to Azure Web App - crud-larabel-web75a43994

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, curl, mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Generate application key
        run: php artisan key:generate

      - name: Set directory permissions
        run: |
          chmod -R 775 storage
          chmod -R 775 bootstrap/cache

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "*.git*" -x "*.github*" -x "tests/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'crud-larabel-web75a43994'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_66CD8103F7A048B693E29297B8A9F243 }}
          package: .
