name: Build and deploy Laravel app to Azure Web App - silmaur-laravel-app

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, curl, mysql, openssl, tokenizer, xml, ctype, fileinfo

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader

      - name: Prepare Laravel folders
        run: |
          mkdir -p storage/framework/{sessions,views,cache}
          mkdir -p bootstrap/cache

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate Laravel APP_KEY
        run: php artisan key:generate

      - name: Optimize Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Zip project
        run: zip -r release.zip . -x ".git/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: laravel-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'silmaur-laravel-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_SILMAURLARAVELAPP }}
          package: .
